### ISSUE TITLE
Hard-wire romi driver board pins to the ESP

### ISSUE THREAD

**Issue by madhephaestus** [WPIRoboticsEngineering/1001-romi-processor-shim#12]
Left PWM to GPIO 13
Left DIR to GPIO 4/ A5
Right PWM to GPIO 12
Right DIR to GPIO 25/A1
ELA to GPIO 27
ELB to GPIO 26/A0
ERA to GPIO 17/TX1
ERB to GPIO 16/RX1
VCC MD to VUSB
GND to GND on the Esp32

**Comment by acamilo** [comment]
VPU to 3.3 is not needed because we're not cutting the trace on the Romi Driver and instead using clamping diodes on the shim.

**Comment by acamilo** [comment]
Define "Left and Right"

**Comment by madhephaestus** [comment]
those are the labels on the PCB

**Comment by acamilo** [comment]
ok thanks
