### ISSUE TITLE
Review pin-out and header placement of shim

### ISSUE THREAD

**Issue by acamilo** [WPIRoboticsEngineering/1001-romi-processor-shim#14]

**Comment by madhephaestus** [comment]
Spread the user headers out a lot more to make room for SS, move the serial bus's off to the right into that free space

**Comment by madhephaestus** [comment]
in fact, move all the headers to the space near the DevKitC's antenna, leaving lots of space for the devkitC heared labels

**Comment by madhephaestus** [comment]
Pinout confirmed.

**Comment by acamilo** [comment]
The USB comes in from the left and the antenna hangs over the side on the right.

**Comment by acamilo** [comment]
i'm going to slide both modules over to the right and put the headers on the left. Sound good?

**Comment by madhephaestus** [comment]
then they will interfere with the USB. THere will be things sticking out of them that will hit the usB cable

**Comment by acamilo** [comment]
The cables enter in through the right. with the front facing you. I'm saying move them to the edge to make room.

![hilight](https://user-images.githubusercontent.com/2826967/85083231-22cd0780-b19f-11ea-9915-f7cede7224d2.png)

**Comment by acamilo** [comment]
I think we have enough room for the labels as it is. I don't think moving the modules is a good idea.
I can move the headers a little.

**Comment by acamilo** [comment]
Look at these labels. That's what i had in mind.
![image](https://user-images.githubusercontent.com/2826967/85083457-d504cf00-b19f-11ea-80d6-05ec49636b9e.png)

**Comment by acamilo** [comment]
Also, The thing plus
![image](https://user-images.githubusercontent.com/2826967/85083526-febdf600-b19f-11ea-9342-34b13a40f032.png)

**Comment by acamilo** [comment]
Check out the board, I moved stuff around to free up some room.

**Comment by madhephaestus** [comment]
looks good

**Comment by acamilo** [comment]
Awesome
