### ISSUE TITLE
Label convention for special function headers

### ISSUE THREAD

**Issue by madhephaestus** [WPIRoboticsEngineering/1001-romi-processor-shim#16]
Each pin should be labeled with its GPIO number, and its function. 

IE
```
VSPI_SCK/5
```

and

```
ECHO/14
```

Around typed headers, make a SS box with a label (like the 3001 motherboard had).

```
VSPI
HC-SR04
Line Sense L
Line Sense R
I2C
Servo
```

**Comment by acamilo** [comment]
Can we entertain a more compact label configuration?

**Comment by acamilo** [comment]
Perhaps, having the sensor headers labeled with the function (ultrasonic, spi, linefollowing)
Then, put the GPIO number (the one used in code) next to each pin.

And then, have a key or a note, to the side with a pin-out of the sensor.

**Comment by acamilo** [comment]
One exception, the headers for a BUS (SPI,I2C) will be labed with the bus signal (SI,SO,SDA,SCL, ..etc)

**Comment by acamilo** [comment]
Let me put together a draft for us to review.

**Comment by acamilo** [comment]
Adafruit places the pin name next to the sensor.
![image](https://user-images.githubusercontent.com/2826967/85185313-7e5fc980-b261-11ea-9833-aec2d7c4279f.png)
![image](https://user-images.githubusercontent.com/2826967/85185362-aea76800-b261-11ea-84ff-062094492fbc.png)
![image](https://user-images.githubusercontent.com/2826967/85185376-b7983980-b261-11ea-8076-a17f7889e9c4.png)
![image](https://user-images.githubusercontent.com/2826967/85185427-df879d00-b261-11ea-9db8-2517ae70d9dc.png)
![image](https://user-images.githubusercontent.com/2826967/85185438-e9a99b80-b261-11ea-9466-6c00e3f528a3.png)

**Comment by acamilo** [comment]
What about something like this? This is for the ultrasonic.
* Polarity is indicated with - and+
* Trigger and Echo indicated with icons
* GPIO Pins Labeled
![image](https://user-images.githubusercontent.com/2826967/85185950-5d4ca800-b264-11ea-95ae-18013d052ed0.png)
* Logo of sensor. This can be text like "SONIC"

**Comment by acamilo** [comment]
What about something like this?
![image](https://user-images.githubusercontent.com/2826967/85188556-87f32c80-b275-11ea-86ce-e63580f5645a.png)

**Comment by acamilo** [comment]
I might want to pick a different font for the text. it is a little cramped.
Maybe we ditch the icons and just do GPIO numbers and labels?

**Comment by acamilo** [comment]
For the other headers, How about something like this?
![image](https://user-images.githubusercontent.com/2826967/85188642-457e1f80-b276-11ea-96b5-b4b992ba17b2.png)

**Comment by madhephaestus** [comment]
awesome!

**Comment by madhephaestus** [comment]
There is no way for the user to see what pins are "availible". A SS label of how each pin is used, highlighting pins that are hard-routed and so not availible.

**Comment by acamilo** [comment]
![image](https://user-images.githubusercontent.com/2826967/87159695-bb7f1080-c28f-11ea-87d5-e3857876b509.png)
