### ISSUE TITLE
Double check the dev kit C footprint

### ISSUE THREAD

**Issue by madhephaestus** [WPIRoboticsEngineering/1001-romi-processor-shim#32]
Use the footprint form the RIB, that one is tested correct. Check the pin spacing is correct

**Comment by madhephaestus** [comment]
its 11 breadboard pins wide

**Comment by acamilo** [comment]
![image](https://user-images.githubusercontent.com/2826967/88335706-bd21ed00-cd01-11ea-8ad3-55c16e7b5b6c.png)
