### ISSUE TITLE
pin 22 connected to ECHO

### ISSUE THREAD

**Issue by gcl8a** [WPIRoboticsEngineering/1001-romi-processor-shim#40]
On my shim board, the ECHO pin is _directly_ connected to pin 22, in addition to pin 17 by way of the resistor.

ECHO
  |
  |-----------pin 22
  |
10k
  |
  |---------|zener---------GND
  |
pin 16

**Comment by madhephaestus** [comment]
THis was a defect in this bioard run, the DRC check wasnt run after the last change and these lines were shorted at the fab. 

ROuting has been fixed and a respin is planned for this afternoon.

**Comment by acamilo** [comment]
fixed. Didn't run DRC after I added the resistor. Trace intersected pad.
