### ISSUE TITLE
Odd behavior of jumper

### ISSUE THREAD

**Issue by gcl8a** [WPIRoboticsEngineering/1001-romi-processor-shim#41]
The left (default) pad is connected to pin 23, the middle to what is labelled MOSI, the right pin 21.

But SDA on the I2C is always connected to 21, so all switching the jumper does is connect MOSI to SDA.

I thought the goal was to switch the SDA pin between 21/23. 

Also, the screen for the I2C has the pins reversed: SDA should be on 21 and SCL on 22.

It appears that it will all work with the DEV board, but not the default pins on a Feather. (Except for the problem with 22 connected to ECHO -- see issue #40 ).

**Comment by acamilo** [comment]
misread request as SDO not SDA. Jumper now selects between 21/23 defaulting to 21
