### ISSUE TITLE
[SILK SCREEN] Label Left and right, as they are labeled by the driver board

### ISSUE THREAD

**Issue by madhephaestus** [WPIRoboticsEngineering/1001-romi-processor-shim#43]
left and right as determined by the driver are opposite the orentation that the board was designed.

![2020-08-10](https://user-images.githubusercontent.com/1254726/89794744-7996f380-daf5-11ea-9e81-296e9ad029a2.jpg)

**Comment by acamilo** [comment]
Changed labels in schematic

**Comment by madhephaestus** [comment]
litteraly wanted silk screens to match the sharpie in the image

**Comment by madhephaestus** [comment]
THIS IS A SILK SCREEN REQUEST

**Comment by madhephaestus** [comment]
bigger, MUCH bigger
